# This setup is heavily influenced by this blog post
# https://dusted.codes/github-actions-for-dotnet-core-nuget-packages#github-release-trigger-for-official-nuget-release

name: .NET

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  # Access key to publish to nuget
  NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
  # .env file for tests
  SDK_TESTS_DOTENV_STAGING: ${{ secrets.SDK_TESTS_DOTENV_STAGING }}

on:
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Write .env file from env var
        # run: echo $SDK_TESTS_DOTENV_STAGING | base64 --decode > .env
        run: echo $SDK_TESTS_DOTENV_STAGING > ./SdkTest/.env
      - name: debug env
        run: cat .env
      - name: Test
        run: dotnet test --configuration Release --no-build --no-restore --verbosity normal SdkTest/SdkTest.csproj

  deploy:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Create Release NuGet package
        run: |
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
          echo Version: $VERSION
          VERSION="${VERSION//v}"
          echo Clean Version: $VERSION
          dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=$VERSION -o nupkg Sdk/Sdk.csproj
      - name: Push to NuGet Feed
        run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
